# Generated by Django 3.2.6 on 2023-02-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pole',
            new_name='role',
        ),
    ]
